export const PEOPLE = [
  "Albinali, Omar",
  "Robin Basdevant",
  "Benacchio, Giovanni",
  "Benito Bosch, Max",
  "Berrocal Hofer, Marius",
  "Blondet, Marine Clara Evelyne",
  "Briggs, Maxwell",
  "Brugada Rodriguez, Laura",
  "Bréchet, Apolline Marie Lucie",
  "Caurette, Marjolaine Katharina Antonia",
  "Celier, Achille Louis Marie",
  "Corral Barba, Jan",
  "Cortes de Ita, Daniel",
  "Cuatrecasas Ferran, Carla",
  "D'Inca, Hugo Victor Quentin",
  "Dammann, Julie",
  "Elamanchi Cavallé, Amparo",
  "Engelhart, Clara",
  "Erenstein, Lorena",
  "Farbman, Evsey",
  "Flores Velasco, Guillermo",
  "Freijo Suñé, Diana",
  "Gigineishvili, Nick",
  "Guandalini, Filippo",
  "Hudak, Patrik",
  "Jauvert, Mathilde Constance Eve",
  "Kato, Mark Csaba",
  "Legodec, Juliette Alexia",
  "Los, Anna Weronika",
  "Lukaszewicz, Maciej",
  "Magnien, Mayleen Mei-Lin",
  "Maigron, Quentin Renaud Pierre",
  "Malone Martin-alos, Lucas",
  "Mamdouhe, Ismaïl Anis",
  "Massarelli, Vale",
  "Mazza, Alessandro",
  "Miksell Gimeno, Lucas Jacob Erik",
  "Moucharraf, Rim",
  "Navarro Pinatell, Mario",
  "Pejacsevich, Chiara Alexandra",
  "Pontroué Martí, Clara",
  "Queiroz Machado, Sebastião",
  "Riscassi, Isabel Allegra",
  "Rojí Romero, María",
  "Rose, Dylan R",
  "Rosset, Prune Charlotte Agnès Michèle",
  "Rubin, Salomé",
  "Scheib, Leni",
  "Shan, Anna",
  "Solberg-Carrara, Alessandro",
  "Stahlhofer Fortuny, Dylan",
  "Urdanivia Lama, Thiago",
  "Würtenberger, Philipp George Thadeus",
  "de Chavagnac, Josephine Joy Marie Zenaide",
] as const;
